### ISSUE TITLE
ARM64

### ISSUE THREAD

**Issue by vysecurity** [fyoorer/ShadowClone#1]
Any where to specify ARM64 in AWS Lambda via Lithops?

Aside from that, modifying the Dockerfile to --plathform=linux/amd64 doesn't seem to make it work on a M1 MacBook.

**Comment by vysecurity** [comment]
Works, missed a reference to AMD64.

**Comment by fyoorer** [comment]
Hey, glad you found the solution. can yo send a PR with steps to get it working on ARM/M1 architecture? I'm sure a lot of people will find it useful.

**Comment by vysecurity** [comment]
> Hey, glad you found the solution. can yo send a PR with steps to get it working on ARM/M1 architecture? I'm sure a lot of people will find it useful.

Will do, I'm just stuck trying to get the runtime executor to run now. I've filed an issue, so we can try and work through it and fix it.

**Comment by lc** [comment]
I'm having this issue currently as well
