### ISSUE TITLE
nmap and masscan usage examples

### ISSUE THREAD

**Issue by georgebecerescu** [fyoorer/ShadowClone#13]
Hi there,
Can you help with nmap and masscan usage examples? I don't seem to get the right syntax to get an output. 
Thanks in advance!

**Comment by fyoorer** [comment]
with the way lambda runs containers, we can't use root privileges on the container so unfortunately that makes masscan unusable but nmap can be used with commands like this:

```
python cloudcli.py -i /tmp/ip_addresses.txt --split 100 -o /tmp/output -c "/static-nmap/nmap -p80,443 -iL {INPUT}"
```

note that without root, nmap will use the -sT mode which will be slower but by splitting the input into smaller chunks it will give very fast and accurate results

p.s. don't do full port scan in one command. that will most certainly time out

**Comment by georgebecerescu** [comment]
Thank you!
