### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by n0sandb0x** [fyoorer/ShadowClone#23]
Hey I followed all the steps you mentioned in the wiki I also checked my aws account and the lambda function is created but I just keep getting the Could not execute the runtime error.

```
(env) ➜  ShadowClone git:(main) ✗ python shadowbrute.py -d netflix.com -w ~/tools/wordlist/best-dns-wordlist.txt
2023-05-02 01:13:42,902 [INFO] File with same name already exists in the bucket, skipping upload
2023-05-02 01:13:42,908 [INFO] config.py:134 -- Lithops v2.8.0
2023-05-02 01:13:42,929 [INFO] aws_s3.py:60 -- S3 client created - Region: ap-south-1
2023-05-02 01:13:44,078 [INFO] aws_lambda.py:94 -- AWS Lambda client created - Region: ap-south-1
2023-05-02 01:13:44,079 [INFO] invokers.py:108 -- ExecutorID ec7ffe-0 | JobID M000 - Selected Runtime: sc-runtime - 512MB
2023-05-02 01:13:44,079 [ERROR] Could not execute the runtime.

```

**Comment by n0sandb0x** [comment]
It worked I looked into the closed issues and yes you need python3.9 not 3.10 By default python3.10 is installed in latest linux versions so make sure python3.9 is installed.


But I ran into another error after installing and running the httpx that you mentioned in the main doc.

Instead of getting output I'm getting the following error 


```
2023-05-02 05:21:44,214 [INFO] executors.py:612 -- ExecutorID 355368-0 - Cleaning temporary data
Encountered a bad command exit code!

Command: '/go/bin/httpx -l {input} -t 100'

Exit code: 1

Stdout: already printed

Stderr: already printed


```

**Comment by n0sandb0x** [comment]
nvm I was using small case input instead of INPUT. Thanks for making such an amazing tools :)

**Comment by sakyb7** [comment]
Can you please let me know how did you solve the problem?

**Comment by amiremami** [comment]
Hey guys, I have same problem. @n0sandb0x Hey Saransh, I just installed and configured shadowclone and wanted to run it for the first time. I got this command from the demo video:

`python3 /root/ShadowClone/shadowclone.py -i /root/apple.txt --split 300 -o httpxout -c "/root/.pdtm/go/bin/httpx -1 {input} -t 100"`

but I got
```
Encountered a bad command exit code!
Command: '/root/.pdtm/go/bin/httpx -1 {input} -t 100'
Exit code: 126
Stdout: already printed
Stderr: already printed
Is it possible for you to tell me how I can fix this?
```
This works alone fine:
/root/.pdtm/go/bin/httpx -l apple.txt -t 100

Then I changed the `input` to `INPUT`

But I got a bit different error:
```
Encountered a bad command exit code!
Command: '/root/.pdtm/go/bin/httpx -1 /tmp/infile -t 100'
Exit code: 126
Stdout: already printed
Stderr: already printed
```
