### ISSUE TITLE
Cannot install Nuclei from the Dockerfile

### ISSUE THREAD

**Issue by sumgr0** [fyoorer/ShadowClone#35]
Whenever I run the command to build from the base Dockerfile from the repo, nuclei fails to install.

Here is the error I'm getting:

![image](https://github.com/fyoorer/ShadowClone/assets/11391119/2176a5d8-4720-4f90-bc32-160be3775ffa)

**Comment by Ajaymagar** [comment]
Its coming because of nuclei need updated golang version. try updated Dockerfile it will work.

**Comment by sumgr0** [comment]
Thanks for the tip @Ajaymagar, that resolved it.

Any ideas on how to run the template(s) from the local system using shadowclones?
