### ISSUE TITLE
Nmap XML output?

### ISSUE THREAD

**Issue by hoacks** [fyoorer/ShadowClone#39]
Is there a way to output in xml format, or JSON in Httpx?

This tools rules!

Thanks

**Comment by hoacks** [comment]
Oh it's in the bucket, of course! Sorry thanks!

**Comment by fyoorer** [comment]
ha! glad you figured it out. I haven't documented this feature anywhere, so this is a good reminder for me to do that haha!

for anyone following, you can provide a {OUTPUT} placeholder in your command to save the generated output to your bucket.

example:
```
python shadowclone.py -i input.txt -c "httpx -l {INPUT} -json -o {OUTPUT}.json
```
you can find the individual outputs for all completed containers saved in the storage bucket under `output/<SCAN ID>/`

**Comment by hoacks** [comment]
Yes, read the source code notice the OUTPUT, this thing is magical! hehe
Thanks.
