### ISSUE TITLE
running findomain with shadowclone

### ISSUE THREAD

**Issue by marcelo321** [fyoorer/ShadowClone#43]
hey, wanted to know if someone sucesfully run findomain with shadowclone.

if yes I would appreciate sharing the command in the dockerfile + the one for executing it <3. I seem to struggle to install it properly and getting:

```
Command: '/usr/local/bin/findomain -f /tmp/infile -q'

Exit code: 127

Stdout: already printed

Stderr: already printed
```

**Comment by amiremami** [comment]
Hey @marcelo321 could you fix this issue finally?

I have same problem. I just installed and configured shadowclone and wanted to run it for the first time. I got this command from the demo video:

`python3 /root/ShadowClone/shadowclone.py -i /root/apple.txt --split 300 -o httpxout -c "/root/.pdtm/go/bin/httpx -1 {input} -t 100"`

but I got
```
Encountered a bad command exit code!
Command: '/root/.pdtm/go/bin/httpx -1 {input} -t 100'
Exit code: 126
Stdout: already printed
Stderr: already printed
Is it possible for you to tell me how I can fix this?
This works alone fine:
/root/.pdtm/go/bin/httpx -l apple.txt -t 100
```
Then I changed the `input` to `INPUT`

But I got a bit different error:
```
Encountered a bad command exit code!
Command: '/root/.pdtm/go/bin/httpx -1 /tmp/infile -t 100'
Exit code: 126
Stdout: already printed
Stderr: already printed
```

**Comment by amiremami** [comment]
@marcelo321 Hey : ) Can you share how you fixed this? Thanks/
