### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by spector012** [fyoorer/ShadowClone#59]
hello,
when i try to run the tool i get the following error

2024-06-17 18:18:35,227 [ERROR] Could not execute the runtime.
The indicated runtime 'sc-runtime' is running Python 3.10 and it is not compatible with the local Python version 3.11

please assist.

**Comment by mswell** [comment]
use [pyenv](https://github.com/pyenv/pyenv) to change python version on local folder.

https://realpython.com/intro-to-pyenv/#local
