### ISSUE TITLE
Typo in Dockerfile_v0.2

### ISSUE THREAD

**Issue by amiremami** [fyoorer/ShadowClone#60]
I guess wget needed to be used instead of eget and also this part missed:

```
# ENV for Go
ENV GOROOT="/usr/local/go"
ENV PATH="${PATH}:${GOROOT}/bin"
ENV PATH="${PATH}:${GOPATH}/bin"
ENV GOPATH=$HOME/go
```

![image](https://github.com/fyoorer/ShadowClone/assets/15929497/6f1b955e-ab82-4a85-af2f-b5bdeb1d9ecd)

**Comment by spector012** [comment]
could this be the reason why it gets stuck 

''' Step 18/34 : RUN eget projectdiscovery/subfinder --to /usr/local/bin
 ---> Running in 09848f0f9f2e
https://github.com/projectdiscovery/subfinder/releases/download/v2.6.6/subfinder_2.6.6_linux_amd64.zip '''

**Comment by fyoorer** [comment]
not a typo
