### ISSUE TITLE
Issue: `nuclei` Command Not Working with ShadowClone

### ISSUE THREAD

**Issue by MustafaSky** [fyoorer/ShadowClone#61]
**Description:**
I encountered an issue while using ShadowClone with the following command:

```bash
python shadowclone.py -i httpx_hackerone_new_subdomains.txt -c "nuclei -duc -l {INPUT} -t /nuclei-templates/http/exposures/configs/phpinfo-files.yaml -config-directory /tmp/"
```

While `httpx` and `subfinder` work fine, the `nuclei` command fails with exit code 2. I have tried multiple times but couldn't resolve the issue.

**Error Details:**
The error messages I receive are:

```
Encountered a bad command exit code!
Command: 'nuclei -duc -l /tmp/infile -t /nuclei-templates/http/exposures/configs/phpinfo-files.yaml -config-directory /tmp/'
Exit code: 2
Stdout: already printed
Stderr: already printed
```

A screenshot of the error is attached for reference.

**Attempts to Resolve:**
- I noticed a similar issue with `subfinder` which was resolved with this PR: https://github.com/fyoorer/ShadowClone/pull/37
- Despite trying similar solutions, I haven't been able to fix the issue with `nuclei`.

![image](https://github.com/fyoorer/ShadowClone/assets/53934731/844f8e62-8296-4547-b14e-67809a73d9a0)

**Comment by MustafaSky** [comment]
```
python shadowclone.py -i httpx_hackerone_new_subdomains.txt -c "/go/bin/nuclei -duc -l {INPUT} -t /nuclei-templates/http/exposures/configs/phpinfo-files.yaml -config-directory /tmp/"
```
![image](https://github.com/fyoorer/ShadowClone/assets/53934731/554a1728-a146-4e0a-93f3-acafe16202a3)

**Comment by fyoorer** [comment]
can  you try 

```
python shadowclone.py -i httpx.txt -s 1 -c "nuclei -duc -l {INPUT} -t /nuclei-templates/http/miscellaneous/robots-txt.yaml"
```

**Comment by MustafaSky** [comment]
Thank you very much; it finally works!
